import os
import calendar
from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_RIGHT
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)


class PDFService:


    @staticmethod
    def generate_monthly_report(report, pdf_path):

    

        os.makedirs(os.path.dirname(pdf_path), exist_ok=True)

        doc = SimpleDocTemplate(
            pdf_path,
            rightMargin=30,
            leftMargin=30,
            topMargin=30,
            bottomMargin=30
        )

        styles = getSampleStyleSheet()

    # -------------------------------------------------------
    # Styles
    # -------------------------------------------------------

        title_style = styles["Heading1"]
        title_style.alignment = TA_CENTER
        title_style.textColor = colors.darkblue
        title_style.fontSize = 22
        title_style.leading = 28

        masjid_style = styles["Heading2"]
        masjid_style.alignment = TA_CENTER
        masjid_style.textColor = colors.darkgreen
        masjid_style.fontSize = 16

        report_style = styles["BodyText"]
        report_style.alignment = TA_CENTER
        report_style.fontSize = 11

        footer_style = styles["Italic"]
        footer_style.alignment = TA_CENTER
        footer_style.fontSize = 9

        month_name = calendar.month_name[report.report_month]

        elements = []

    # -------------------------------------------------------
    # Title
    # -------------------------------------------------------

        elements.append(
            Paragraph(
                "MASJID MONTHLY FINANCIAL REPORT",
                title_style
            )
        )

        elements.append(
            Paragraph(
                "<b>Durga Nagar Masjid</b>",
                masjid_style
            )
        )

        elements.append(Spacer(1, 0.08 * inch))

        elements.append(
            Paragraph(
                f"<b>Report Period:</b> {month_name} {report.report_year}",
                report_style
            )
        )

        elements.append(Spacer(1, 0.10 * inch))

    # -------------------------------------------------------
    # Green separator line
    # -------------------------------------------------------

        line = Table(
          [[""]],
            colWidths=[7 * inch]
        )

        line.setStyle(
            TableStyle([
                ("LINEBELOW", (0, 0), (-1, -1), 2, colors.darkgreen)
            ])
        )

        elements.append(line)

        elements.append(Spacer(1, 0.25 * inch))

    # -------------------------------------------------------
    # Financial Table
    # -------------------------------------------------------

        data = [

            ["Description", "Amount (INR)"],

            ["Opening Balance", f"{report.OpeningBalance:,.2f}"],

            ["Friday Contribution", f"{report.Friday_contribution:,.2f}"],

            ["General Contribution", f"{report.General_contribution:,.2f}"],

            ["Imam Contribution", f"{report.Imam_contribution:,.2f}"],

            ["Total Income", f"{report.TotalIncome:,.2f}"],

            ["Total Expense", f"{report.TotalExpense:,.2f}"],

            ["Closing Balance", f"{report.ClosingBalance:,.2f}"]

        ]

        table = Table(
            data,
            colWidths=[4.7 * inch, 2.0 * inch]
        )

        table.setStyle(

            TableStyle([

            ("BACKGROUND", (0, 0), (-1, 0), colors.darkblue),

            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),

            ("FONTSIZE", (0, 0), (-1, 0), 12),

            ("BOTTOMPADDING", (0, 0), (-1, 0), 10),

            ("GRID", (0, 0), (-1, -1), 1, colors.grey),

            ("BACKGROUND", (0, 1), (-1, -2), colors.beige),

            ("BACKGROUND", (0, -1), (-1, -1), colors.lightgrey),

            ("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold"),

            ("ALIGN", (1, 1), (1, -1), "RIGHT"),

            ("BOTTOMPADDING", (0, 1), (-1, -1), 8),

            ])

        )

        elements.append(table)

        elements.append(Spacer(1, 0.40 * inch))

    # -------------------------------------------------------
    # Footer
    # -------------------------------------------------------

        generated = datetime.now().strftime("%d-%b-%Y %I:%M %p")

        elements.append(

            Paragraph(

                f"Generated on: {generated}<br/><br/>"
                "This report is system generated by "
                "<b>Durga Nagar Masjid Management System</b>.",

                footer_style

            )

        )

        doc.build(elements)

        return pdf_path